plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "me.modmuss50.mod-publish-plugin"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    modImplementation "com.terraformersmc:modmenu:${rootProject.modmenu_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
    repositories {
    }
}

File changeLog = rootProject.file("CHANGELOG.md")
String changelogtext = ""
if (changeLog.exists()) {
    def sections = changeLog.text.split(/(?m)^## /)
    changelogtext = sections.length > 1 ? "## " + sections[1].trim() : changeLog.text
}

def isAlpha = project.findProperty('alphaBuild')?.toString()?.toBoolean() ?: false

publishMods {
    file = tasks.named('remapJar').flatMap { it.archiveFile }
    changelog = changelogtext
    version = project.version.toString()
    type = isAlpha ? ALPHA : STABLE
    displayName = "${rootProject.mod_name} ${project.version} [FABRIC]"
    modLoaders.add("fabric")
    dryRun = false
    maxRetries = 3

    github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "FinnSetchell/Vinery-Wine-Toggle"
        commitish = "1.20.1"
        tagName = providers.environmentVariable("GITHUB_REF_NAME").orElse("${minecraft_version}-${project.version}")
        displayName = "${rootProject.mod_name} ${project.version} [FABRIC]"
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = rootProject.modrinthProjectId
        minecraftVersions.addAll("1.20.1")
    }

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = rootProject.curseforgeProjectId
        projectSlug = rootProject.curseforgeProjectSlug
        serverRequired = true
        minecraftVersions.addAll("1.20.1")
    }
}
