plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "me.modmuss50.mod-publish-plugin"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "winetoggle-common.mixins.json"
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    modImplementation "me.shedaniel.cloth:cloth-config-forge:${rootProject.cloth_config_version}"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.5"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.3.5"))

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
    repositories {
    }
}

File changeLog = rootProject.file("CHANGELOG.md")
String changelogtext = ""
if (changeLog.exists()) {
    def sections = changeLog.text.split(/(?m)^## /)
    changelogtext = sections.length > 1 ? "## " + sections[1].trim() : changeLog.text
}

def isAlpha = project.findProperty('alphaBuild')?.toString()?.toBoolean() ?: false
def discordWebhookEnvVar = isAlpha ? 'DISCORD_ALPHA_WEBHOOK_URL' : 'DISCORD_WEBHOOK'
def discordPingExplicit = project.findProperty('discordPing')?.toString()?.toBoolean() ?: true
def discordPing = isAlpha ? false : discordPingExplicit

publishMods {
    file = tasks.named('remapJar').flatMap { it.archiveFile }
    changelog = changelogtext
    version = project.version.toString()
    type = isAlpha ? ALPHA : STABLE
    displayName = "${rootProject.modName} ${project.version} [FORGE]"
    modLoaders.add("forge")
    dryRun = false
    maxRetries = 3

    github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "FinnSetchell/Vinery-Wine-Toggle"
        commitish = "1.20.1"
        tagName = providers.environmentVariable("GITHUB_REF_NAME").orElse("${minecraft_version}-${project.version}")
        displayName = "${rootProject.modName} ${project.version} [FORGE]"
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = rootProject.modrinthProjectId
        minecraftVersions.addAll("1.20.1")
    }

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = rootProject.curseforgeProjectId
        projectSlug = rootProject.curseforgeProjectSlug
        serverRequired = true
        minecraftVersions.addAll("1.20.1")
    }

}
